### ISSUE TITLE
Installation incomplete

### ISSUE THREAD

**Issue by byoungsunglim** [wimvanboven/razer-blade-14-2022-btusb#1]
As I run "sudo dkms install btusb/0.8" I get the error message below. 
I found that my /usr/src/linux-headers-5.15.0-46/drivers/bluetooth/ folder is empty. 
However, even when I copy all the drivers downloaded from [here](https://github.com/torvalds/linux/tree/master/drivers/bluetooth), 
and rerun your command "sudo dkms install btusb/0.8" I also get error. 
Can you help me with this?

Kernel preparation unnecessary for this kernel. Skipping...

Running the pre_build script:
grep: /usr/src/kernels/5.15.0-46-generic/Makefile: No such file or directory
Downloading kernel source 5.15. for 5.15.0-46-generic
--2022-08-14 00:37:14--  https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/linux-5.15..tar.xz
Resolving mirrors.edge.kernel.org (mirrors.edge.kernel.org)... 147.75.48.161, 2604:1380:40f1:3f00::1
Connecting to mirrors.edge.kernel.org (mirrors.edge.kernel.org)|147.75.48.161|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-08-14 00:37:15 ERROR 404: Not Found.

Extracting original source
tar: linux-5.15..tar.*: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Increase module version
sed: can't read btusb.c: No such file or directory
Applying razer14_2022.btusb.patch
can't find file to patch at input line 3
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|--- btusb.c.ori	2022-06-01 21:33:33.827463689 +0200
|+++ btusb.c	2022-06-01 21:36:42.499297875 +0200
--------------------------
File to patch:

**Comment by wimvanboven** [comment]
you need to have kernel dev package on your distro installed and the script expects to find them in /usr/src/kernels/<version>.
you can edit dkms-patchmodule.sh to make it work on your distro if needed. 

consider going to 5.17+ though, not sure if it matters, but i have seen commits on this chipset with some fixes. 
to reset dkms, run 'dkms status' check if the module is registered, remove with 'dkms remove -m btusb/0.8'

edit:
on fedora, the package that provides this is
```
[wim@fedora kernels]$ dnf provides /usr/src/kernels/5.18.16-200.fc36.x86_64
Last metadata expiration check: 1 day, 3:14:04 ago on Fri 12 Aug 2022 02:54:20 PM CEST.
**kernel-devel-5.18.16-200.fc36.x86_64 : Development package for building kernel modules to match the kernel**
Repo        : @System
Matched from:
Filename    : /usr/src/kernels/5.18.16-200.fc36.x86_64

kernel-devel-5.18.16-200.fc36.x86_64 : Development package for building kernel modules to match the kernel
Repo        : updates
Matched from:
Filename    : /usr/src/kernels/5.18.16-200.fc36.x86_64
```
